name: 'zoomap'
version: '1.0.0'
config-version: 2

profile: 'zoomap'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  wikipedia_lang: "en"

models:
  zoomap:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table
